---
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Ensure package is absent
  when: "'eea' in ansible_facts.packages"
  ansible.builtin.package:
    name: eea
    state: absent
